config/routes.rb
Rails.application.routes.draw do
  resources :finances
  get '', action: :main, controller: 'static'
  resources :cars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, :carts, :goods, :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
end

app/models/finance.rb
class Finance < ApplicationRecord
    has_one :orders
    scope :income, -> { where(dc: true) }
    scope :outcome, -> { where.not(dc: true) }
    scope :period, -> (period) {where(created_at: (DateTime.now - period.days).beginning_of_day()..DateTime.now) }
end

app/models/good.rb
class Good < ApplicationRecord
    has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :goods
  has_many :finances
end

app/models/user.rb
class User < ApplicationRecord
    has_many :cars
    has_many :orders
    
    def name_with_initial 
        firstname + " " + secondname
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  def index
    @cars = Car.all
  end

  def show
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    if @car.save 
        redirect_to :controller => "users", :action => "new"
    else
        redirect_to :action => "index", notice: "Your user no send"
    end
  end
  
  def edit
  end

  def update
    if @car.update_attributes(car_params)
      redirect_to user_path(User.find(@car.user_id))
  else
      render :edit
  end
  end

  def destroy
    @car.destroy
    redirect_to user_path(User.find(@car.user_id))
  end

  private
    def set_car
      @car = Car.find(params[:id])
    end

    def car_params
      params.fetch(:car, {}).permit(:vin, :vendor, :model, :year, :mileage, :user_id, :comment)
    end
end

app/controllers/finances_controller.rb
class FinancesController < ApplicationController
  before_action :set_finance, only: [:show, :edit, :update, :destroy]

  # GET /finances
  # GET /finances.json
  def index
    @start_date = params[:start_date] ? Date.parse(params[:start_date]) : DateTime.now() - 1
    @end_date = params[:end_date] ? Date.parse(params[:end_date]) : DateTime.now()
    @finances = Finance.where(created_at: @start_date..@end_date)
  end

  # GET /finances/1
  # GET /finances/1.json
  def show
  end

  # GET /finances/new
  def new
    @finance = Finance.new
  end

  # GET /finances/1/edit
  def edit
  end

  # POST /finances
  # POST /finances.json
  def create
    @finance = Finance.new(finance_params)

    respond_to do |format|
      if @finance.save
        format.html { redirect_to @finance, notice: 'Finance was successfully created.' }
        format.js
        format.json { render :show, status: :created, location: @finance }
      else
        format.html { render :new }
        format.json { render json: @finance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /finances/1
  # PATCH/PUT /finances/1.json
  def update
    respond_to do |format|
      if @finance.update(finance_params)
        format.html { redirect_to @finance, notice: 'Finance was successfully updated.' }
        format.json { render :show, status: :ok, location: @finance }
      else
        format.html { render :edit }
        format.json { render json: @finance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /finances/1
  # DELETE /finances/1.json
  def destroy
    @finance.destroy
    respond_to do |format|
      format.html { redirect_to finances_url, notice: 'Finance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_finance
      @finance = Finance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def finance_params
      params.require(:finance).permit(:value, :dc, :user_id, :target, :comment, :order_id)
    end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
    before_action :set_good, only: [:show, :edit, :update, :destroy]

    def index
        @goods = Good.all
    end

    def show
    end

    def new
        @good = Good.new
    end
    
    def create
        @good = Good.new(good_params)
        respond_to do |format|
            if @good.save 
                format.html { redirect_to controller: "orders", action: "show", id: @good.order_id, notice: "Your good just send" }
                format.js 
                format.json { render json: @user, status: :created, location: @user }
            else
                format.html { redirect_to :action => "index", notice: "Your good no send" }
                format.json { render json: @user.errors, status: :unprocessable_entity }
            end
        end        
    end

    def edit
    end

    def update

    end

    def destroy
        @good.destroy
        redirect_to :back
    end

    private

    def good_params
        params.require(:good).permit(:partnumber, :price, :cost, :outercost, :expdate, :order_id)
    end

    def set_good
        @good = Good.find(params[:id])
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :set_order, only: [:show, :edit, :update, :destroy]

    def index
        if params[:status].present?
            @orders = Order.where(status: params[:status])
        else
            @orders = Order.all
        end
    end

    def show
        @goods = Good.where(order_id: @order.id)
        @finances = Finance.where(order_id: @order.id)
    end

    def new
        @order = Order.new
    end
    
    def create
        @order = Order.new(order_params)
        if @order.save 
            redirect_to :action => "index", notice: "Your order just send"
        else
            redirect_to :action => "index", notice: "Your order no send"
        end
    end

    def edit
    end

    def update

    end

    def destroy
        @order.destroy
        redirect_to orders_path
    end

    private

    def order_params
        params.require(:order).permit(:user_id, :status, :comment, :manager, :message)
    end

    def set_order
        @order = Order.find(params[:id])
    end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def main
        
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    def index
        @users = User.all
    end

    def show
    end

    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        respond_to do |format|
            if @user.save 
                format.html { redirect_to :controller => "users", :action => "new", notice: 'User was successfully created' }
                format.js 
                format.json { render json: @user, status: :created, location: @user }
            else
                format.html { render action: 'new' }
                format.json { render json: @user.errors, status: :unprocessable_entity }
            end
        end                    
    end

    def edit
    end

    def update

    end

    def destroy
        @user.destroy
        redirect_to :action => "index"
    end

    private

    def user_params
        params.require(:user).permit(:phone, :firstname, :secondname, :email, :adress, :comment)
    end

    def set_user
        @user = User.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
    def value_request
        puts "-----------Helper work"
        return User.where(phone: params[:phone]).first.present? ? User.where(phone: params[:phone]).first.id : nil 
    end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cars/_form.html.erb
<%= form_for(car) do |f| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.text_field :vin, placeholder: "VIN номер" %><br>
    <%= f.text_field :vendor, placeholder: "Производитель" %><br>
    <%= f.text_field :model, placeholder: "Модель" %><br>
    <%= f.text_field :year, placeholder: "Год выпуска" %><br>
    <%= f.text_field :mileage, placeholder: "Пробег, тыс.км" %><br>
    <%= f.select :user_id, User.all.collect {|p| [ p.firstname + " " + p.secondname, p.id ] }, { include_blank: true } %><br>
    <%= f.text_field :comment, placeholder: "Комментарий" %><br>
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<div class="title-div"><h4>Автомобили</h4></div>
<table>
  <thead>
    <tr>
      <th>#</th>
      <th>VIN</th>
      <th>Производитель</th>
      <th>Модель</th>
      <th>Год</th>
      <th>Пробег</th>
      <th>Собственник</th>
      <th>Комментарий</th>
      <th>Операции</th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.id %></td>
        <td><%= car.vin %></td>
        <td><%= car.vendor %></td>
        <td><%= car.model %></td>
        <td><%= car.year %></td>
        <td><%= car.mileage %></td>
        <td><%= link_to (User.find(car.user_id).firstname + " " + User.find(car.user_id).secondname), user_path(User.find(car.user_id)) %></td>
        <td><%= car.comment %></td>
        <td><%= link_to 'Show', car %> <%= link_to 'Edit', edit_car_path(car) %> <%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/clients/index.html.erb
<div class="title-div"><h4>Клиенты</h4></div>
<table>
<tr>
<th>№</th><th>Клиент</th><th>Телефон</th><th>Адрес</th><th></th>
</tr>
<% @clients.each do |o| %>
<tr onclick="window.location.href='clients/<%= o.id %>'; return false">
<td><%= o.id %></td>
<td><%= o.firstname << " " << o.secondname %></td>
<td><%= o.phone %></td>
<td><%= o.adress %></td>
<td><%= link_to "Редактировать", edit_client_path(o.id) %></td>
</tr>
<% end %>
</table>
<%= link_to 'Добавить клиента', :controller => 'clients', :action => 'new' %>

app/views/clients/new.html.erb
<div>
  <h4 class="title">Новый клиент</h4>
<%= form_for @client do |client| %>
  <% if params[:phone].present? %>
  <%= client.telephone_field :phone, value: params[:phone] %><br>
  <% else %>
  <%= client.telephone_field :phone, placeholder: "введите телефон" %><br>
  <% end %>
  <%= client.text_field :firstname, placeholder: "Ваше имя" %><br>
  <%= client.text_field :secondname, placeholder: "Ваша фамилия" %><br>
  <%= client.email_field :email, placeholder: "Ваша почта" %><br>
  <%= client.text_field :adress, placeholder: "Адрес"  %><br>
  <%= client.submit "Сохранить клиента" %><br>
<% end %>
</div>

app/views/finances/_finances_remote_form.html.erb
<% Rails.logger.info "----------------#{params.inspect}" %>
<%= form_for @finance, :controller => :finance, :action => 'create', :method => :post, :id => 'finance-form', :remote => true do |finance| %>
    <%= finance.label :dc, "Приход"%>
    <%= finance.radio_button :dc, 1, checked: params[:dc] == '1' %>
    <%= finance.label :dc, "Расход"%>
    <%= finance.radio_button :dc, 0, :checked => params[:dc] == '0' %>
    <%= finance.number_field :value, placeholder: "Сумма"%>
    <%= finance.collection_select :user_id, User.all, :id, :name_with_initial, value: params[:user_id] ? params[:user_id] : '' %>
    <%= finance.text_field :target, placeholder: "Назначение" %>
    <%= finance.text_field :comment, placeholder: "Комментарий"%>
    <%= finance.hidden_field :order_id, value:@order.id%>
    <%= finance.submit "Добавить платеж"%>
<% end %>

app/views/finances/_form.html.erb
<%= form_for(finance) do |payment| %>
  <% if finance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(finance.errors.count, "error") %> prohibited this finance from being saved:</h2>

      <ul>
      <% finance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= payment.label :dc, "Приход"%>
    <%= payment.radio_button :dc, 1, checked: params[:dc] == '1' %>
    <br>
    <%= payment.label :dc, "Расход"%>
    <%= payment.radio_button :dc, 0, :checked => params[:dc] == '0' %>
    <br>
    <%= payment.number_field :value, placeholder: "Сумма"%><br>
    <%= payment.collection_select :user_id, User.all, :id, :name_with_initial, value: params[:user_id] ? params[:user_id] : '' %><br>
    <%= payment.text_field :target, placeholder: "Назначение" %><br>
    <%= payment.text_field :comment, placeholder: "Комментарий"%><br>
    <%= payment.hidden_field :order_id, placeholder: "Комментарий", value: params[:order_id]%><br>
    <%= payment.submit "Добавить платеж"%>
<% end %>

app/views/finances/create.js.erb
<% Rails.logger.info "---------------#{@order.inspect}"%>
$(".finances-table > tbody").append('<tr><td><%= @order.finances.lenght %></td><td><%= @finance.value %></td><td><%= @finance.target %></td><td><%= @finance.created_at %></td><td> <%= link_to 'delete', @finance, :method => :delete, data: {:confirm => "You sure?" }, :title => "Delete #{@finance.id}" %></td></tr>');

app/views/finances/edit.html.erb
<h1>Editing Finance</h1>

<%= render 'form', finance: @finance %>

<%= link_to 'Show', @finance %> |
<%= link_to 'Back', finances_path %>

app/views/finances/index.html.erb
<p id="notice"><%= notice %></p>
<div class="title-div">Сводка на период <%= @start_date.to_date %> : <%= @end_date.to_date %></div>
<div class="statistics">
  
  <div class="statictics-header">
    Получено:<%= @finances.income.collect {|i| i.value}.sum %> Потрачено:<%= @finances.outcome.collect {|i| i.value}.sum %>
  </div>

  <div class="statistics-filters">
    <%= form_tag({:controller => "finances", :action => "index"}, method: 'get', class: "filter") do %>
      От: <%= date_field_tag :start_date %> До: <%= date_field_tag :end_name %> <%= submit_tag "Поиск" %>
    <% end %>
  </div>
  
  <div class="statistics-body">
    <table>
      <thead>
        <tr>
          <th colspan="10"></th>
        </tr>
      </thead>

      <tbody>
        <% @finances.each_with_index do |finance, index| %>
          <tr>
            <td><%= index + 1%></td>
            <td><%= finance.value %></td>
            <td><%= link_to User.find(finance.user_id).name_with_initial, user_path(finance.user_id)%></td>
            <td><%= finance.target %></td>
            <td><%= finance.created_at%></td>
            <td><%= finance.order_id.nil? ? '' : (link_to Order.find(finance.order_id).id, order_path(finance.order_id)) %></td>
            <td><%= finance.comment %></td>
            <td><%= link_to 'Edit', edit_finance_path(finance) %></td>
            <td><%= link_to 'Destroy', finance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<%# <%= link_to 'New Finance', new_finance_path %>
</div>

app/views/finances/new.html.erb
<h1>Новый платеж</h1>

<%= render 'form', finance: @finance %>

app/views/finances/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_finance_path(@finance) %> |
<%= link_to 'Back', finances_path %>

app/views/goods/_goods_remote_form.html.erb
<%= form_for @good, :controller => :good, :action => 'create', :method => :post, :id => 'good-form', :remote => true do |good| %>
  <%= good.text_field :partnumber, placeholder: "Партномер" %><br>
  <%= good.number_field :outercost, placeholder: "Отпускная цена" %><br>
  <%= good.number_field :cost, placeholder: "Входящая цена" %><br>
  <%= good.date_field :expdate, placeholder: "Планируемая дата поставки" %><br>
   <%= good.hidden_field :order_id, value: order_id %><br>
  <%= good.submit "Сохранить" %><br>
<% end %>

app/views/goods/create.js.erb
$(".wrapper").hide();
$(".positions-in-order-table > tbody").prepend('<tr><td><%= @good.partnumber %></td><td><%= @good.cost %></td><td><%= @good.outercost %></td><td><%= @good.expdate %></td><td> <%= link_to 'delete', @good, :method => :delete, data: {:confirm => "You sure?" }, :title => "Delete #{@good.id}" %></td></tr>');

app/views/goods/new.html.erb
<div>
  <h4 class="title">Добавление позиции</h4>
    <%= render partial: 'goods_remote_form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Parttrade</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
  </head>

  <body>
  <header>
  <div id="main-head">
  <p>
  <%= link_to "Заказы", {controller: "orders", action: "index"}, class: "main-menu" %>
  <%= link_to "Клиенты", {controller: "users", action: "index"}, class: "main-menu"  %>
  <%= link_to "Финансы", {controller: "finances", action: "index"}, class: "main-menu" %>
  </p>

  
  </div>
  </header>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<div class="title-div"><h4>Заказы</h4></div>
<%= button_tag(:type => 'button', :class => "btn-new-order") do %>
  <% link_to "Новый заказ", new_order_path %>
<% end %>
<table>
<tr>
<th>№</th><th>Клиент</th><th>Статус</th><th>Комментарий</th>
</tr>
<% @orders.each_with_index do |o, index| %>
<tr onclick="window.location.href='orders/<%= o.id %>'; return false">
<td><%= index+1 %></td>
<td><%= User.find(o.user_id).firstname %></td>
<td><%= o.status %></td>
<td><%= o.comment %></td>
</tr>
<% end %>
</table>

app/views/orders/new.html.erb
<div>
  <h4 class="title">Новый заказ</h4>
<%= form_for @order do |order| %>
  <span>Менеджер</span><br>
  <%= order.collection_select :manager, User.where(admin: true), :id, :name_with_initial %><br>
  <span>Статус</span><br>
  <%= order.select :status, ["Новый", "Принят в обработку", "Ожидает согласования", "В пути", "Выдан"]%><br>
  <span>Клиент</span><br>
  <%= order.collection_select :user_id, User.all, :id, :name_with_initial, include_blank: true, selected: value_request %>
      <%= image_tag "add.png", class: "add_icon", onclick: '$(".wrapper").show()'%><br>
  <span>Комментарий</span><br>
  <%= order.text_area :comment, placeholder: "Введите Ваш комментарий", value: params[:message].present? ? params[:message] : nil %><br>
  <%= order.submit "Сохранить заказ" %><br>
<% end %>
</div>

<div class='wrapper'> 
<div class="modality">
<div class="close-button-area">
<span class="close-button" onclick='$(".wrapper").hide()'>X</span>
</div>

<%= render partial: "users/user_remote_form", user: @user = User.new %>
</div>
</div>

app/views/orders/show.html.erb
<div class="title-div">
  <h4>Заказ: № <%= @order.id %> от <%= @order.created_at.to_date %><br>
  Клиент: <%= link_to @order.user.name_with_initial, user_path(@order.user_id)%><br>
  Менеджер: <%= link_to User.find(@order.manager).name_with_initial, user_path(@order.manager)%><br>
  Статус: <%= @order.status %><br>
  Итого: <%= @goods.collect {|good| good.outercost}.sum %> руб. <br>
  Оплачено: <%= @finances.collect {|fin| fin.value}.sum %> руб. <br>
  Задолженность: <%= @goods.collect {|good| good.outercost}.sum - @finances.collect {|fin| fin.value}.sum %> руб. <br>
  Прибыль: <%= @goods.collect {|good| good.outercost - good.cost}.sum %> руб. <br>
  Комментарий: <%=@order.comment %><br>
  </h4>
</div>

<div class="body-div">
  <%# <h3>В заказе: </h3><%= link_to "Добавить позицию", new_good_path(:order_id => @order.id) %>
  <%= button_tag( 'Добавить позицию', :type => 'button', :class => "btn-new-position", onclick: '$(".wrapper").show()') %>
  <table class="positions-in-order-table" >
    <thead><th>PartNumber</th><th>Входная цена</th><th>Отпускная цена</th><th>Дата прихода</th></thead>
    <% if @goods != [] %>
        <% @goods.each do |good| %>
        <tr>
          <td><%= good.partnumber %></td>
          <td><%= good.cost %></td>
          <td><%= good.outercost %></td>
          <td><%= good.expdate %></td>
          <td> <%= link_to 'delete', good, :method => :delete, data: {:confirm => "You sure?" }, :title => "Delete #{good.id}" %></td>
        </tr>
        <% end %>
    <% end %>   
  </table>
</div>
<div class="finance-details">
    <%= render partial: 'finances/finances_remote_form', locals: { order_id: @order.id, finance: @finance = Finance.new } %>
     <% if @finances != [] %>
    <table class="finances-table">
        <thead><td>#</td><td>Платеж</td><td>Назначение</td><td>Дата платежа</td></thead>
        <% @finances.each_with_index do |fin, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= fin.value %></td>
          <td><%= fin.target %></td>
          <td><%= fin.created_at %></td>
          <td> <%= link_to 'delete', fin, :method => :delete, data: {:confirm => "You sure?" }, :title => "Delete #{fin.id}" %></td>
        </tr>
        <% end %>
    </table>
    <% end %>
</div>

<div class='wrapper'> 
  <div class="modality">
    <div class="close-button-area">
      <span class="close-button" onclick='$(".wrapper").hide()'>X</span>
    </div>
    <%= render partial: "goods/goods_remote_form", locals: {good: @good = Good.new, order_id: @order.id} %>
  </div>
</div>

app/views/requests/index.html.erb
<div class="title-div"><h4>Заявки</h4></div>
<table>
<tr>
<th>№</th><th>Телефон</th><th>Почта</th><th>Сообщение</th><th>Действия</th>
</tr>
<% @requests.each do |r| %>
<tr>
<td><%= r.id %></td>
<td><%= r.phone %></td>
<td><%= r.email %></td>
<td><%= r.message %></td>
<td>
<%= link_to 'Создать заказ', controller: 'orders', action: 'new', phone: r.phone, message: r.message %>     
<%= link_to "Удалить запрос", requests_path(r.id), method: :delete, data: { confirm: 'Уверены что хотите удалить этот запрос?' }%>
</td>
</tr>
<% end %>
</table>

app/views/requests/new.html.erb
<div>
  <h4 class="title">Форма заказа:</h4>
<%= form_for @request do |form| %>
  <%= form.text_field :name, placeholder: "Ваше имя" %><br>
  <%= form.email_field :email, placeholder: "Ваша почта" %><br>
  <%= form.telephone_field :phone, placeholder: "Ваш телефон"  %><br>
  <%= form.text_field :vin, placeholder: "VIN Code"  %><br>
  <%= form.text_area :message, placeholder: "Введите Ваш заказ" %><br>
  <%= form.submit "Отправить заказ" %><br>
<% end %>
</div>

app/views/users/_cars_list.html.erb
<ul><% @user.cars.each do |car| %>
<li><%= car.id %> <%= car.vendor %><%= car.model %> <%= car.vin %><%= car.year %> <%= car.mileage %> <%= link_to 'edit', edit_car_path(car.id) %><%= link_to 'delete', car,  method: :delete, data: { confirm: 'Are you sure?' } %>
</li>
<% end %>
</ul>

app/views/users/_orders_list.html.erb
<table>
  <thead>
    <td>№</td>
    <td>Статус</td>
    <td>Срок</td>
    <td>Сумма заказа</td>
  </thead>
    <tr>
    <td>№</td>
    <td>Статус</td>
    <td>Срок</td>
    <td>Сумма заказа</td>
  </tr>
</table>

app/views/users/_user_remote_form.html.erb
<%= form_for @user, :controller => :user, :action => 'create', :method => :post, :id => 'user-form', :remote => true do |user| %>
  <% if params[:phone].present? %>
  <%= user.telephone_field :phone, value: params[:phone] %><br>
  <% else %>
  <%= user.telephone_field :phone, placeholder: "Телефон" %><br>
  <% end %>
  <%= user.text_field :firstname, placeholder: "Имя" %><br>
  <%= user.text_field :secondname, placeholder: "Фамилия" %><br>
  <%= user.email_field :email, placeholder: "Почта" %><br>
  <%= user.text_field :adress, placeholder: "Адрес"  %><br>
  <%= user.text_field :comment, placeholder: "Комментарий"  %><br>
  <%= user.submit "Сохранить" %><br>
<% end %>

app/views/users/create.js.erb
$(".wrapper").hide();
$("#order_user_id").prepend('<option value="<%= @user.id %>" selected="selected"><%= @user.name_with_initial %></option>');
console.log('Success');

app/views/users/index.html.erb
<div class="title-div"><h4>Клиенты</h4></div>
<table>
<tr>
<th>№</th><th>Клиент</th><th>Телефон</th><th>Адрес</th><th>Коммент</th><th></th>
</tr>
<% @users.each do |o| %>
<tr>
<td><%= link_to o.id, user_path(o.id)%></td>
<td><%= o.firstname << " " << o.secondname %></td>
<td><%= o.phone %></td>
<td><%= o.adress %></td>
<td><%= o.comment %></td>
<td><%= link_to "Редактировать", edit_user_path(o.id) %> <%= link_to 'Х', { action: :destroy, id: o.id }, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>
<% end %>
</table>
<%= link_to 'Добавить клиента', :controller => 'users', :action => 'new' %>

app/views/users/new.html.erb
<div>
  <h4 class="title">Новый клиент</h4>
  <%= render partial: 'user_form' %>
</div>

app/views/users/show.html.erb
<div>
  <h4 class="title">Клиент № <%= @user.id %>: <%= @user.firstname + " " + @user.secondname%><%= link_to "Создать заказ", controller: "orders", action: "new"%></h4>
<p>
<table>
<thead>
<td><h4>Информация:</h4></td>
<td><h4>Авто  <%= link_to '+', :controller => 'cars', :action => 'new' %></h4> </td>
</thead>
<tr>
<td>
<b>Имя: </b><%= @user.firstname %><br>
<b>Фамилия: </b><%= @user.secondname %><br>
<b>Телефон: </b><%= @user.phone %><br>
<b>Почта: </b><%= @user.email %><br>
<b>Адрес: </b><%= @user.adress %><br>
<b>Комментарий: </b><%= @user.comment %><br>
<b>Роль: </b><%= @user.role %><br>
<b>Админ? </b><%= @user.admin.nil? ? "Не админ" : "Админ"%><br>
</td>
<td>
<%= render partial: "cars_list" %>
</td>
</tr>
</table>
<%= render partial: "orders_list" %>
</p>
</div>